const MESSAGES = {
    // Basic
    1001: 'Success',

    // Login
    2001: 'Login successfully',
    2002: 'Invalid token',

    // user
    3001: 'User not Found',

    // api error
    9999: 'Something went wrong !!',
    4444: 'Access denied for this route',

    // Report Reason
    1003: "Title is required",
    1004: "Report reason ID is required",
    1005: "Report reason not found",
    1006: "Report reason created successfully",
    1007: "Report reason updated successfully",
    1008: "Report reason deleted successfully",

    // Notification
    1009: "Title, message and type are required",
    1010: "Notification sent successfully",
    1011: "SellerId, title and message are required",
    1012: "Invalid Seller ID format",
    1013: "Seller not found",
    1014: "Notification sent to seller successfully",
    1015: "Unauthorized access!",
    1016: "User does not found!",
    1017: "you are blocked by admin!",

    // Batch 1: Address, Admin, Attributes, AuctionBid, Bank
    1018: "userId must be required.",
    1019: "User not found!",
    1020: "Invalid details",
    1021: "Address created by the user.",
    1022: "addressId must be required.",
    1023: "Address not found.",
    1024: "Address has been updated by the user.",
    1025: "Addresses retrieved successfully.",
    1026: "addressId and userId must be required.",
    1027: "Selected address retrieved successfully.",
    1028: "Address deleted successfully.",
    1029: "Username, email and password are required.",
    1030: "Admin already exists.",
    1031: "Invalid email or password.",
    1032: "UserId is required!",
    1033: "Users retrieved successfully.",
    1034: "User account has been deleted.",
    1035: "Admin not found.",
    1036: "Profile updated successfully.",
    1037: "Image updated successfully.",
    1038: "Email is required.",
    1039: "Server configuration error: Email credentials missing.",
    1040: "Error sending email.",
    1041: "Email sent successfully.",
    1042: "Old and new password are required.",
    1043: "Invalid old password.",
    1044: "Password updated successfully.",
    1045: "Password, confirm password and email are required.",
    1046: "Password and confirm password does not match.",
    1047: "Please provide valid subCategoryIds and attribute details.",
    1048: "Attribute name is required and must be a string.",
    1049: "Invalid fieldType. Must be one of 1–6.",
    1050: "Attribute already exists.",
    1051: "Values array is required for selectable fieldTypes (4, 5, 6).",
    1052: "Attribute added successfully.",
    1053: "attributeId must be required.",
    1054: "Attribute not found.",
    1055: "Attribute deleted successfully.",
    1056: "Attributes retrieved successfully.",
    1057: "User auction fetched successfully.",
    1058: "Missing or invalid userId/productId/bidAmount.",
    1059: "Product not found.",
    1060: "Auction is not enabled for this product.",
    1061: "Auction dates are not configured.",
    1062: "Invalid auction date format.",
    1063: "Auction has not started yet.",
    1064: "Auction has already ended.",
    1065: "Invalid current bid state.",
    1066: "Your bid must be higher than current bid.",
    1067: "Bid placed successfully.",
    1068: "Bank created successfully.",
    1069: "Bank ID is required!",
    1070: "Bank not found!",
    1071: "Bank updated successfully.",
    1072: "Banks retrieved successfully.",
    1073: "Bank deleted successfully.",

    // Batch 2: Cart, Category, Currency, Dashboard, FAQ
    1074: "Oops! Invalid details!",
    1075: "Sellers cannot add their own products to the cart!",
    1076: "Product added to cart.",
    1077: "Cart not found for this user.",
    1078: "Invalid attributes format.",
    1079: "Product quantity not found in the cart.",
    1080: "Product with specified attributes not found in the cart.",
    1081: "Product removed from cart and cart deleted.",
    1082: "Product removed from the cart.",
    1083: "No products found in the cart.",
    1084: "Retrive all products added to cart.",
    1085: "Remove all products from the cart for this user!",
    1086: "CategoryId is required.",
    1087: "Category not found.",
    1088: "Category created successfully.",
    1089: "Category updated successfully.",
    1090: "Categories retrieved successfully.",
    1091: "Currency fetched successfully.",
    1092: "Name, symbol and currencyCode are required.",
    1093: "Currency stored successfully.",
    1094: "currencyId is required.",
    1095: "Currency not found.",
    1096: "Currency updated successfully.",
    1097: "Default currency cannot be deleted.",
    1098: "Currency deleted successfully.",
    1099: "Default currency set successfully.",
    1100: "Data retrieved successfully.",
    1101: "FAQ created successfully.",
    1102: "faqId is required.",
    1103: "FAQ not found.",
    1104: "FAQ updated successfully.",
    1105: "FAQ deleted successfully.",

    // Batch 3: Favorite, Follower, LiveSeller, Order, OTP
    1106: "Invalid product ID.",
    1107: "This seller is blocked by the admin.",
    1108: "Purchase code missing or invalid.",
    1109: "Live history not found.",
    1110: "Setting not found.",
    1111: "User ID is required.",
    1112: "Final total is required.",
    1113: "No items to order.",
    1114: "Invalid promo code.",
    1115: "Promo code already used.",
    1116: "Invalid final total.",
    1117: "Order not found.",
    1118: "Order does not belong to this user.",
    1119: "Item not found in order.",
    1120: "Order cannot be cancelled.",
    1121: "Invalid status.",
    1122: "Email is required.",
    1123: "Email service not configured.",
    1124: "Failed to send email.",
    1125: "OTP and email are required.",
    1126: "OTP does not match.",
    1127: "Live Selling History ID is required.",

    // Batch 4: Product, ProductRequest, PromoCode, Rating, Reel
    1128: "Subcategory not found.",
    1129: "Invalid attributes format.",
    1130: "Product request not found.",
    1131: "Product request already accepted.",
    1132: "Promo code is required.",
    1133: "Discount type is required.",
    1134: "Discount amount is required.",
    1135: "Conditions are required.",
    1136: "Promo code ID is required.",
    1137: "Promo code not found.",
    1138: "Product ID and rating are required.",
    1139: "Rating must be between 1 and 5.",
    1140: "You have already rated this product.",
    1141: "Reel not found.",
    1142: "Reel ID is required.",
    1143: "No valid approved products found.",

    // Batch 5: ReportReel, Review, Seller, SellerRequest, SellerWallet
    1144: "You have already given a review on this product.",
    1145: "Review ID is required.",
    1146: "Review not found.",
    1147: "Image is required.",
    1148: "All fields are required.",
    1149: "Report ID is required.",
    1150: "Report not found.",
    1151: "Report already solved by the admin.",
    1152: "Seller request not found.",
    1153: "Seller request already accepted.",
    1154: "User not found associated with this request.",
    1155: "You have already sent a seller request.",
    1156: "User is not a seller.",
    1157: "User is already a seller.",
    1158: "No seller request found for this user.",

    // Batch 6: Setting, SubCategory, User, Withdraw, WithdrawRequest
    1159: "Subcategory ID is required.",
    1160: "No subcategories found for this category.",
    1161: "Email and password are required.",
    1162: "User password not set or found.",
    1163: "Old password does not match.",
    1164: "Mobile number is required.",
    1165: "User must sign up first.",
    1166: "Invalid query parameters.",
    1167: "Setting not found.",
    1168: "Invalid field or toggle type.",
    1169: "New password and confirm password do not match.",
    1170: "Withdrawal method not found.",
    1171: "Settings not found.",
    1172: "Insufficient funds to withdraw.",
    1173: "Requested amount must be greater than minimum payout.",
    1174: "Withdrawal request is already pending.",
    1175: "Withdrawal request not found.",
    1176: "Withdrawal request already accepted.",
    1177: "Withdrawal request already declined.",
    1178: "Insufficient balance to approve.",
    1179: "Request ID and reason are required."
};

const get_message = message_code => {
    if (isNaN(message_code)) {
        return message_code;
    }
    return message_code ? MESSAGES[message_code] : message_code;
};

module.exports = { get_message };
