const swaggerJSDoc = require("swagger-jsdoc");

const options = {
  definition: {
    openapi: "3.0.3",
    info: {
      title: "TrendyCart Admin API",
      version: "1.0.0",
      description: "API documentation for your Dating Admin backend",
    },
    servers: [
      {
        url: `${process.env.API_URL}` || "http://localhost:3001/api/v1",
        description: "Local server",
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
    },
    tags: [
      { name: "Admin Auth", description: "Admin authentication" },
      { name: "Admin Sign Up", description: "Admin creation" },
      { name: "Admin Profile", description: "Admin profile management" },
      { name: "Admin Dashboard", description: "Admin dashboard statistics" },
      { name: "Admin User Management", description: "Admin user management" },
      { name: "Admin Seller Request", description: "Admin seller request management" },
      { name: "Admin Seller", description: "Admin seller management" },
      { name: "Admin Category", description: "Admin category management" },
      { name: "Admin SubCategory", description: "Admin subcategory management" },
      { name: "Admin Attributes", description: "Admin attributes management" },
      { name: "Admin Product Request", description: "Admin product request management" },
      { name: "Admin Product", description: "Admin product management" },
      { name: "Admin Order", description: "Admin order management" },
      { name: "Admin Withdraw", description: "Admin withdrawal management" },
      { name: "Admin Withdraw Request", description: "Admin withdrawal request management" },
      { name: "Admin Seller Wallet", description: "Admin seller wallet and earnings" },
      { name: "Admin Reel", description: "Admin reel management" },
      { name: "Admin LiveSeller", description: "Admin live seller management" },
      { name: "Admin Promo Code", description: "Admin promo code management" },
      { name: "Admin Report Reason", description: "Admin report reason management" },
      { name: "Admin FAQ", description: "Admin FAQ management" },
      { name: "Admin Report Reel", description: "Admin reported reel management" },
      { name: "Admin Review", description: "Admin review management" },
      { name: "Admin Currency", description: "Admin currency management" },
      { name: "Admin Notification", description: "Admin notification management" },
      { name: "Admin Setting", description: "Admin application settings" },
      { name: "Admin Bank", description: "Admin bank management" },
      { name: "Withdraw Request", description: "Withdrawal request management" },
      { name: "User Auth", description: "User authentication" },
      { name: "User Profile", description: "User profile management" },
      { name: "User Seller Request", description: "User seller request management" },
      { name: "OTP", description: "OTP management" },
      { name: "Address", description: "Address management" },
      { name: "Product", description: "Product management" },
      { name: "Order", description: "Order management" },
      { name: "Cart", description: "Cart management" },
      { name: "Favorite", description: "Favorite management" },
      { name: "Reel", description: "Reel management" },
      { name: "ReportReel", description: "Reel reporting" },
      { name: "Review", description: "Review management" },
      { name: "Rating", description: "Rating management" },
      { name: "LiveSeller", description: "Live seller management" },
      { name: "AuctionBid", description: "Auction bid management" },
      { name: "PromoCodeCheck", description: "Promo code validation" },
      { name: "Setting", description: "Application settings" },
      { name: "Bank", description: "Bank management" },
      { name: "Category", description: "User category management" },
      { name: "Currency", description: "Currency management" },
      { name: "Dashboard", description: "User dashboard statistics" },
      { name: "FAQ", description: "FAQ management" },
      { name: "Follower", description: "Follower management" },
      { name: "Notification", description: "Notification management" },
      { name: "Product Request", description: "Product update request management" },
      { name: "ReportReason", description: "Report reason management" },
      { name: "Seller", description: "User seller management" },
      { name: "Seller Wallet", description: "Seller wallet management" },
      { name: "SubCategory", description: "SubCategory management" },
      { name: "Withdraw", description: "Withdrawal management for users" },
      { name: "User Promo Code", description: "Promo code management for users" },
    ],
  },
  apis: ["./src/routes/**/*.js", "./src/controllers/**/*.js"],
};

const swaggerSpec = swaggerJSDoc(options);

module.exports = swaggerSpec;
